appName: emailservice
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
appVersion: v0.10.2
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 5000
