apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  repicas: {{ .Values.appReplicas}}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage}}:{{ .Values.appVersion}}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.containerPort }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.containerMountPath }}
          name: {{ .Values.volumeName }}
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: {{ .Values.volumeName }}
        emptyDir: {}
